### ISSUE TITLE
SDLNet_SendDatagram fails if the socket is created with NULL address

### ISSUE THREAD

**Issue by captain0xff** [libsdl-org/SDL_net#92] opened 2024-05-01 15:58 UTC
`SDLNet_SendDatagram` fails with the error `Failed to send from socket: The system detected an invalid pointer address in attempting to use a pointer argument in a call.` on windows if the socket is created by passing NULL as the first parameter of `SDLNet_CreateDatagramSocket`. I can reproduce it with voip-chat example.

**Comment by apartfromtime** [comment] 2024-05-08 09:12
Duplicate of #86? Could you confirm this if this is IPv4 only?

**Comment by captain0xff** [comment] 2024-05-08 20:59
Yes, you are right. The problem happens only with IPv4, at least on localhost. For example, I can send to "::1" without problems but when I try to send on "127.0.0.1" I encounter a aforementioned error.

**Closed** 2024-05-08 21:02 UTC
